### PR TITLE
Turtlecoin

### PR DESCRIPTION
**Pull request by plenteum**
All the Turtle Stuff - Except for the following:

Donation Addresses
You may want to review the content, like the TC's etc. as I've just guessed at wallet domain names and such... 
I am busy sync'ing a test site here : http://206.189.124.145
(Apologies for the messy sequence of Commits in this PR)

### CODE REVIEW

**Comment by brandonlehmann** [comment]
Hashrate and block reward look like decimal errors. If you point me in the right direction I can fix :)

**Comment by plenteum** [comment]
Hi, thanks for the Heads up, I will sort and PR today.

**Comment by RocksteadyTC** [comment]
image

**Comment by RocksteadyTC** [comment]
I'm torching the repo and making a new one with the changes.

**Comment by RocksteadyTC** [comment]
This one?

**Pull request closed without merging**
